export const mockConfigGlobalData = [
  {
    kpiId: 'kpi158',
    kpiName: 'Mean Time To Merge',
    isEnabled: true,
    order: 1,
    kpiDetail: {
      id: '65793ddc127be336160bc113',
      kpiId: 'kpi158',
      kpiName: 'Mean Time To Merge',
      isDeleted: 'False',
      defaultOrder: 2,
      kpiCategory: 'Developer',
      kpiUnit: 'Hours',
      chartType: 'card',
      upperThresholdBG: 'red',
      lowerThresholdBG: 'white',
      showTrend: true,
      isPositiveTrend: false,
      calculateMaturity: true,
      hideOverallFilter: true,
      kpiSource: 'BitBucket',
      combinedKpiSource: 'Bitbucket/AzureRepository/GitHub/GitLab',
      maxValue: '10',
      thresholdValue: 55,
      kanban: false,
      groupId: 6,
      kpiInfo: {
        definition:
          'MEAN TIME TO MERGE measures the efficiency of the code review process in a team',
        details: [
          {
            type: 'paragraph',
            value:
              'It is calculated in â€˜Hoursâ€™. Fewer the Hours better is the â€˜Speedâ€™',
          },
          {
            type: 'paragraph',
            value:
              'A progress indicator shows trend of Mean time to merge in last 2 weeks. A downward trend is considered positive',
          },
          {
            type: 'paragraph',
            value:
              'Maturity of the KPI is calculated based on the average of the last 5 weeks',
          },
          {
            type: 'link',
            kpiLinkDetail: {
              text: 'Detailed Information at',
              link: 'https://knowhow.tools.publicis.sapient.com/wiki/kpi158-Mean+Time+To+Merge',
            },
          },
        ],
        maturityLevels: [
          {
            level: 'M5',
            bgColor: '#6cab61',
            range: '<4 Hours',
          },
          {
            level: 'M4',
            bgColor: '#AEDB76',
            range: '4-8 Hours',
          },
          {
            level: 'M3',
            bgColor: '#eff173',
            range: '8-16 Hours',
          },
          {
            level: 'M2',
            bgColor: '#ffc35b',
            range: '16-48 Hours',
          },
          {
            level: 'M1',
            bgColor: '#F06667',
            range: '>48 Hours',
          },
        ],
      },
      kpiFilter: 'dropDown',
      aggregationCriteria: 'average',
      maturityRange: ['-16', '16-8', '8-4', '4-2', '2-'],
      isRepoToolKpi: true,
      trendCalculative: false,
      xaxisLabel: 'Weeks',
      yaxisLabel: 'Count(Hours)',
      isAdditionalFilterSupport: false,
    },
    shown: true,
  },
  {
    kpiId: 'kpi160',
    kpiName: 'Pickup Time',
    isEnabled: true,
    order: 2,
    kpiDetail: {
      id: '65793ddc127be336160bc115',
      kpiId: 'kpi160',
      kpiName: 'Pickup Time',
      isDeleted: 'false',
      defaultOrder: 3,
      kpiCategory: 'Developer',
      kpiUnit: 'Hours',
      chartType: 'card',
      upperThresholdBG: 'red',
      lowerThresholdBG: 'white',
      showTrend: true,
      isPositiveTrend: false,
      calculateMaturity: true,
      hideOverallFilter: true,
      kpiSource: 'BitBucket',
      combinedKpiSource: 'Bitbucket/AzureRepository/GitHub/GitLab',
      maxValue: 10,
      thresholdValue: 20,
      kanban: false,
      groupId: 6,
      kpiInfo: {
        definition:
          'Pickup time measures the time a pull request waits for someone to start reviewing it. Low pickup time represents strong teamwork and a healthy review',
        details: [
          {
            type: 'paragraph',
            value:
              'It is calculated in â€˜Hoursâ€™. Fewer the Hours better is the â€˜Speedâ€™',
          },
          {
            type: 'paragraph',
            value:
              'A progress indicator shows trend of Pickup Time in the last 2 weeks. A downward trend is considered positive',
          },
          {
            type: 'paragraph',
            value:
              'Maturity of the KPI is calculated based on the average of the last 5 weeks',
          },
          {
            type: 'link',
            kpiLinkDetail: {
              text: 'Detailed Information at',
              link: 'https://knowhow.tools.publicis.sapient.com/wiki/kpi160-Pickup+Time',
            },
          },
        ],
        maturityLevels: [
          {
            level: 'M5',
            bgColor: '#6cab61',
            range: '<4 Hours',
          },
          {
            level: 'M4',
            bgColor: '#AEDB76',
            range: '4-8 Hours',
          },
          {
            level: 'M3',
            bgColor: '#eff173',
            range: '8-16 Hours',
          },
          {
            level: 'M2',
            bgColor: '#ffc35b',
            range: '16-48 Hours',
          },
          {
            level: 'M1',
            bgColor: '#F06667',
            range: '>48 Hours',
          },
        ],
      },
      kpiFilter: 'dropDown',
      aggregationCriteria: 'average',
      maturityRange: ['-16', '16-8', '8-4', '4-2', '2-'],
      isRepoToolKpi: true,
      trendCalculative: false,
      xaxisLabel: 'Weeks',
      yaxisLabel: 'Count (Hours)',
      isAdditionalFilterSupport: false,
    },
    shown: true,
  },
  {
    kpiId: 'kpi185',
    kpiName: 'Innovation Rate',
    isEnabled: true,
    order: 3,
    kpiDetail: {
      id: '6720d1339ac57e3618dfac1e',
      kpiId: 'kpi185',
      kpiName: 'Innovation Rate',
      isDeleted: 'false',
      defaultOrder: 9,
      kpiCategory: 'Developer',
      kpiUnit: '%',
      chartType: 'card',
      upperThresholdBG: 'white',
      lowerThresholdBG: 'red',
      showTrend: true,
      isPositiveTrend: true,
      calculateMaturity: false,
      hideOverallFilter: true,
      kpiSource: 'BitBucket',
      combinedKpiSource: 'Bitbucket/AzureRepository/GitHub/GitLab',
      maxValue: '',
      kanban: false,
      groupId: 7,
      kpiInfo: {
        definition:
          'Innovation rate aims at identifying the volume of brand new additions to a codebase (functional and non-functional features, etc) by measuring the newly added code at repository level.\nMore precisely, the New source lines of code(LOC) from a commit. (git log stats insertions)',
        details: [
          {
            type: 'link',
            kpiLinkDetail: {
              text: 'Detailed Information at',
              link: 'https://knowhow.tools.publicis.sapient.com/wiki/kpi185-Innovation+Rate',
            },
          },
        ],
      },
      kpiFilter: 'dropDown',
      aggregationCriteria: 'average',
      isRepoToolKpi: true,
      trendCalculative: false,
      xaxisLabel: 'Days/Weeks/Months',
      yaxisLabel: 'Percentage',
      isAdditionalFilterSupport: false,
    },
    shown: true,
  },
  {
    kpiId: 'kpi186',
    kpiName: 'Defect Rate',
    isEnabled: true,
    order: 4,
    kpiDetail: {
      id: '6720d1339ac57e3618dfac20',
      kpiId: 'kpi186',
      kpiName: 'Defect Rate',
      isDeleted: 'false',
      defaultOrder: 10,
      kpiCategory: 'Developer',
      kpiUnit: '%',
      chartType: 'card',
      upperThresholdBG: 'red',
      lowerThresholdBG: 'white',
      showTrend: true,
      isPositiveTrend: false,
      calculateMaturity: false,
      hideOverallFilter: true,
      kpiSource: 'BitBucket',
      combinedKpiSource: 'Bitbucket/AzureRepository/GitHub/GitLab',
      maxValue: '',
      kanban: false,
      groupId: 6,
      kpiInfo: {
        definition:
          'The percentage of merged pull requests that are addressing defects.',
        details: [
          {
            type: 'link',
            kpiLinkDetail: {
              text: 'Detailed Information at',
              link: 'https://knowhow.tools.publicis.sapient.com/wiki/kpi186-Defect+Rate',
            },
          },
        ],
      },
      kpiFilter: 'dropDown',
      aggregationCriteria: 'average',
      isRepoToolKpi: true,
      trendCalculative: false,
      xaxisLabel: 'Days/Weeks/Months',
      yaxisLabel: 'Percentage',
      isAdditionalFilterSupport: false,
    },
    shown: true,
  },
  {
    kpiId: 'kpi157',
    kpiName: 'Check-Ins & Merge Requests',
    isEnabled: true,
    order: 5,
    kpiDetail: {
      id: '65793ddc127be336160bc112',
      kpiId: 'kpi157',
      kpiName: 'Check-Ins & Merge Requests',
      isDeleted: 'False',
      defaultOrder: 1,
      kpiCategory: 'Developer',
      kpiUnit: 'MRs',
      chartType: 'grouped_column_plus_line',
      showTrend: true,
      isPositiveTrend: true,
      lineLegend: 'Merge Requests',
      barLegend: 'Commits',
      calculateMaturity: true,
      hideOverallFilter: true,
      kpiSource: 'BitBucket',
      combinedKpiSource: 'Bitbucket/AzureRepository/GitHub/GitLab',
      maxValue: 10,
      thresholdValue: 55,
      kanban: false,
      groupId: 6,
      kpiInfo: {
        definition:
          'NUMBER OF CHECK-INS helps in measuring the transparency as well the how well the tasks have been broken down. NUMBER OF MERGE REQUESTS when looked at along with commits highlights the efficiency of the review process',
        details: [
          {
            type: 'paragraph',
            value:
              'It is calculated as a Count. Higher the count better is the â€˜Speedâ€™',
          },
          {
            type: 'paragraph',
            value:
              'A progress indicator shows trend of Number of Check-ins & Merge requests between last 2 days. An upward trend is considered positive',
          },
          {
            type: 'link',
            kpiLinkDetail: {
              text: 'Detailed Information at',
              link: 'https://knowhow.tools.publicis.sapient.com/wiki/kpi157-Check-Ins+&+Merge+Requests',
            },
          },
        ],
        maturityLevels: [
          {
            level: 'M5',
            bgColor: '#6cab61',
            range: '> 16',
          },
          {
            level: 'M4',
            bgColor: '#AEDB76',
            range: '8-16',
          },
          {
            level: 'M3',
            bgColor: '#eff173',
            range: '4-8',
          },
          {
            level: 'M2',
            bgColor: '#ffc35b',
            range: '2-4',
          },
          {
            level: 'M1',
            bgColor: '#F06667',
            range: '0-2',
          },
        ],
      },
      kpiFilter: 'dropDown',
      aggregationCriteria: 'average',
      maturityRange: ['-2', '2-4', '4-8', '8-16', '16-'],
      isRepoToolKpi: true,
      trendCalculative: false,
      xaxisLabel: 'Days',
      yaxisLabel: 'Count',
      isAdditionalFilterSupport: false,
    },
    shown: true,
  },
  {
    kpiId: 'kpi162',
    kpiName: 'PR Size',
    isEnabled: true,
    order: 6,
    kpiDetail: {
      id: '65793ddc127be336160bc116',
      kpiId: 'kpi162',
      kpiName: 'PR Size',
      isDeleted: 'false',
      defaultOrder: 4,
      kpiCategory: 'Developer',
      kpiUnit: 'Lines',
      chartType: 'scatter',
      upperThresholdBG: 'red',
      lowerThresholdBG: 'white',
      showTrend: false,
      isPositiveTrend: false,
      calculateMaturity: false,
      hideOverallFilter: true,
      kpiSource: 'BitBucket',
      combinedKpiSource: 'Bitbucket/AzureRepository/GitHub/GitLab',
      maxValue: 10,
      thresholdValue: 4,
      kanban: false,
      groupId: 6,
      kpiInfo: {
        definition:
          'Pull request size measures the number of code lines modified in a pull request. Smaller pull requests are easier to review, safer to merge, and correlate to a lower cycle time.',
        details: [
          {
            type: 'link',
            kpiLinkDetail: {
              text: 'Detailed Information at',
              link: 'https://knowhow.tools.publicis.sapient.com/wiki/kpi162-PR+Size',
            },
          },
        ],
      },
      kpiFilter: 'dropDown',
      aggregationCriteria: 'average',
      maturityRange: ['-16', '16-8', '8-4', '4-2', '2-'],
      isRepoToolKpi: true,
      trendCalculative: false,
      xaxisLabel: 'Weeks',
      yaxisLabel: 'Count (No. of Lines)',
      isAdditionalFilterSupport: false,
    },
    shown: true,
  },
  {
    kpiId: 'kpi182',
    kpiName: 'PR Success Rate',
    isEnabled: true,
    order: 7,
    kpiDetail: {
      id: '6720d1329ac57e3618dfac18',
      kpiId: 'kpi182',
      kpiName: 'PR Success Rate',
      isDeleted: 'false',
      defaultOrder: 5,
      kpiCategory: 'Developer',
      kpiUnit: '%',
      chartType: 'semi-circle-donut-chart',
      upperThresholdBG: 'white',
      lowerThresholdBG: 'red',
      showTrend: true,
      isPositiveTrend: true,
      calculateMaturity: false,
      hideOverallFilter: true,
      kpiSource: 'BitBucket',
      combinedKpiSource: 'Bitbucket/AzureRepository/GitHub/GitLab',
      maxValue: '',
      thresholdValue: 50,
      kanban: false,
      groupId: 7,
      kpiInfo: {
        definition:
          'PR success rate measures the number of pull requests that went through the process without being abandoned or discarded as against the total PRs raised in a defined period  A low or declining Pull Request Success Rate represents high or increasing waste',
        details: [
          {
            type: 'link',
            kpiLinkDetail: {
              text: 'Detailed Information at',
              link: 'https://knowhow.tools.publicis.sapient.com/wiki/kpi182-PR+Success+Rate',
            },
          },
        ],
      },
      kpiFilter: 'dropDown',
      aggregationCriteria: 'average',
      maturityRange: ['-5', '5-20', '20-50', '50-80', '80-'],
      isRepoToolKpi: true,
      trendCalculative: false,
      xaxisLabel: 'Weeks',
      yaxisLabel: 'Percentage',
      isAdditionalFilterSupport: false,
    },
    shown: true,
  },
  {
    kpiId: 'kpi173',
    kpiName: 'Rework Rate',
    isEnabled: true,
    order: 8,
    kpiDetail: {
      id: '65eeb08194c86b415f97893a',
      kpiId: 'kpi173',
      kpiName: 'Rework Rate',
      isDeleted: 'false',
      defaultOrder: 5,
      kpiCategory: 'Developer',
      kpiUnit: '%',
      chartType: 'progressbar',
      showTrend: true,
      isPositiveTrend: false,
      calculateMaturity: false,
      hideOverallFilter: true,
      kpiSource: 'BitBucket',
      combinedKpiSource: 'Bitbucket/AzureRepository/GitHub/GitLab',
      maxValue: '',
      kanban: false,
      groupId: 7,
      kpiInfo: {
        definition:
          'Percentage of code changes in which an engineer rewrites code that they recently updated (within the past three weeks).',
        details: [
          {
            type: 'link',
            kpiLinkDetail: {
              text: 'Detailed Information at',
              link: 'https://knowhow.tools.publicis.sapient.com/wiki/kpi173-Rework+Rate',
            },
          },
        ],
      },
      kpiFilter: 'dropDown',
      aggregationCriteria: 'average',
      maturityRange: ['-80', '80-50', '50-20', '20-5', '5-'],
      isRepoToolKpi: true,
      trendCalculative: false,
      xaxisLabel: 'Weeks',
      yaxisLabel: 'Percentage',
      isAdditionalFilterSupport: false,
    },
    shown: true,
  },
  {
    kpiId: 'kpi201',
    kpiName: 'Code Quality Metrics',
    isDeleted: 'False',
    defaultOrder: 28,
    kpiUnit: '%',
    chartType: 'progressbar',
    upperThresholdBG: 'red',
    lowerThresholdBG: 'white',
    showTrend: true,
    isPositiveTrend: false,
    calculateMaturity: false,
    hideOverallFilter: false,
    kpiSource: 'Jira',
    maxValue: 100,
    thresholdValue: 20,
    kanban: false,
    groupId: 26,
    kpiInfo: {
      definition:
        'Defects Breached SLAs (%) refers to the percentage of defects within a system or service that fail to meet the agreed-upon Service Level Agreement (SLA) timeframes.',
      formula: [
        {
          lhs: 'Defects Breached SLA (%)',
          operator: 'division',
          operands: [
            'Number of Resolved Defects that breached SLA',
            'Total Resolved Defects',
          ],
        },
      ],
      details: [
        {
          type: 'link',
          kpiLinkDetail: {
            text: 'Detailed Information at',
            link: 'https://knowhow.suite.publicissapient.com/wiki/spaces/PS/pages/270794755/Defects+Breached+SLAs',
          },
        },
      ],
    },
    aggregationCriteria: 'average',
    isTrendCalculative: false,
    isAdditionalFilterSupport: true,
    combinedKpiSource: 'Jira',
  },
  {
    kpiId: 'kpi181',
    kpiName: 'PR Decline Rate',
    isEnabled: true,
    order: 10,
    kpiDetail: {
      id: '6720d1329ac57e3618dfac17',
      kpiId: 'kpi181',
      kpiName: 'PR Decline Rate',
      isDeleted: 'false',
      defaultOrder: 5,
      kpiCategory: 'Developer',
      kpiUnit: '%',
      chartType: 'line',
      upperThresholdBG: 'red',
      lowerThresholdBG: 'white',
      showTrend: true,
      isPositiveTrend: false,
      calculateMaturity: false,
      hideOverallFilter: true,
      kpiSource: 'BitBucket',
      combinedKpiSource: 'Bitbucket/AzureRepository/GitHub/GitLab',
      maxValue: '',
      thresholdValue: 50,
      kanban: false,
      groupId: 7,
      kpiInfo: {
        definition:
          'The percentage of opened Pull Requests that are declined within a timeframe.',
        details: [
          {
            type: 'link',
            kpiLinkDetail: {
              text: 'Detailed Information at',
              link: 'https://knowhow.tools.publicis.sapient.com/wiki/kpi181-PR+Decline+Rate',
            },
          },
        ],
      },
      kpiFilter: 'dropDown',
      aggregationCriteria: 'average',
      maturityRange: ['-80', '80-50', '50-20', '20-5', '5-'],
      isRepoToolKpi: true,
      trendCalculative: false,
      xaxisLabel: 'Weeks',
      yaxisLabel: 'Percentage',
      isAdditionalFilterSupport: false,
    },
    shown: true,
  },
];
